2024-02-20 12:32:50,281 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-20 12:32:50,282 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-20 12:32:50,282 - INFO - the user ID extracted from token in decode: 9
2024-02-20 12:32:50,282 - INFO - the user id after decoding: 9
2024-02-20 16:02:02,073 - INFO - the user record found in DB: <app.db.models.User object at 0x7f4c4f85a9b0>
2024-02-20 16:02:02,073 - INFO - Finding if user record exist in DB
2024-02-20 16:02:02,073 - INFO - checking the user credentials if correct than access will be given
2024-02-20 16:02:02,073 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-20 16:02:02,382 - INFO - JWT token created for the data of the user
2024-02-20 16:02:02,382 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-20 16:02:02,383 - INFO - JWT refresh token created for the user data
2024-02-20 16:02:02,383 - INFO - returning the refresh token generated from jwt_access_token() funtion
2024-02-20 16:02:26,453 - INFO - the user record found in DB: <app.db.models.User object at 0x7f823c45a9b0>
2024-02-20 16:02:26,453 - INFO - Finding if user record exist in DB
2024-02-20 16:02:26,453 - INFO - checking the user credentials if correct than access will be given
2024-02-20 16:02:26,453 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-20 16:02:26,763 - INFO - JWT token created for the data of the user
2024-02-20 16:02:26,763 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-20 16:02:26,764 - INFO - JWT refresh token created for the user data
2024-02-20 16:02:26,764 - INFO - returning the refresh token generated from jwt_access_token() funtion
2024-02-21 11:12:40,657 - INFO - the user record found in DB: <app.db.models.User object at 0x7f8b7ff4dc00>
2024-02-21 11:12:40,657 - INFO - Finding if user record exist in DB
2024-02-21 11:12:40,657 - INFO - checking the user credentials if correct than access will be given
2024-02-21 11:12:40,657 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-21 11:12:40,968 - INFO - JWT token created for the data of the user
2024-02-21 11:12:40,968 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-21 11:12:40,968 - INFO - JWT refresh token created for the user data
2024-02-21 11:12:40,968 - INFO - returning the refresh token generated from jwt_access_token() funtion
2024-02-21 11:13:23,341 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-21 11:13:23,341 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-21 11:13:23,341 - INFO - the user ID extracted from token in decode: 9
2024-02-21 11:13:23,341 - INFO - the user id after decoding: 9
2024-02-21 11:13:23,342 - ERROR - Error occured while rollouting billboard: BaseModel.__init__() takes 1 positional argument but 6 were given
2024-02-21 11:14:34,254 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-21 11:14:34,255 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-21 11:14:34,255 - INFO - the user ID extracted from token in decode: 9
2024-02-21 11:14:34,256 - INFO - the user id after decoding: 9
2024-02-21 11:14:34,256 - ERROR - Error occured while rollouting billboard: BaseModel.__init__() takes 1 positional argument but 6 were given
2024-02-21 11:14:59,349 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-21 11:14:59,350 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-21 11:14:59,350 - INFO - the user ID extracted from token in decode: 9
2024-02-21 11:14:59,351 - INFO - the user id after decoding: 9
2024-02-21 11:14:59,351 - ERROR - Error occured while rollouting billboard: BaseModel.__init__() takes 1 positional argument but 6 were given
2024-02-21 11:15:53,001 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-21 11:15:53,001 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-21 11:15:53,002 - INFO - the user ID extracted from token in decode: 9
2024-02-21 11:15:53,002 - INFO - the user id after decoding: 9
2024-02-21 11:15:53,002 - ERROR - Error occured while rollouting billboard: BaseModel.__init__() takes 1 positional argument but 6 were given
2024-02-21 11:21:17,164 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-21 11:21:17,164 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-21 11:21:17,165 - INFO - the user ID extracted from token in decode: 9
2024-02-21 11:21:17,165 - INFO - the user id after decoding: 9
2024-02-21 11:21:17,165 - INFO - data: {'location': 'Japan', 'price': 150, 'size': '100x100', 'status': 'Avaliable', 'register_date': '21-feb-2024', 'fk_user_id': 9}
2024-02-21 11:21:17,166 - ERROR - Error occured while rollouting billboard: 1 validation error for Publish_Billboard
picture
  Field required [type=missing, input_value={'location': 'Japan', 'pr...-2024', 'fk_user_id': 9}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2024-02-21 11:25:32,975 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-21 11:25:32,975 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-21 11:25:32,976 - INFO - the user ID extracted from token in decode: 9
2024-02-21 11:25:32,976 - INFO - the user id after decoding: 9
2024-02-21 11:25:32,976 - INFO - data: {'location': 'Japan', 'price': 150, 'size': '100x100', 'status': 'Avaliable', 'register_date': '21-feb-2024', 'picture': 'uploads/1.jpeg', 'fk_user_id': 9}
2024-02-21 11:25:32,978 - INFO - RolloutBillBoard table is recieving data from crud rollout_billboard
2024-02-21 11:33:13,956 - INFO - Attempting to register user ahmed@gmail.com
2024-02-21 11:33:13,957 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-21 11:33:14,314 - INFO - new user registered in DB with the id: 10
2024-02-21 11:33:14,314 - INFO - new user is created Ahmed Ali
2024-02-21 11:33:14,314 - INFO - User sucessfully added
2024-02-21 11:34:17,184 - INFO - the user record found in DB: <app.db.models.User object at 0x7f6812041990>
2024-02-21 11:34:17,184 - INFO - Finding if user record exist in DB
2024-02-21 11:34:17,184 - INFO - checking the user credentials if correct than access will be given
2024-02-21 11:34:17,467 - INFO - JWT token created for the data of the user
2024-02-21 11:34:17,467 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-21 11:34:17,468 - INFO - JWT refresh token created for the user data
2024-02-21 11:34:17,468 - INFO - returning the refresh token generated from jwt_access_token() funtion
2024-02-21 11:35:35,726 - INFO - Records found in DB returning forgot data to user
2024-02-21 11:36:51,919 - INFO - the google-user record found in DB: None
2024-02-21 11:36:51,963 - INFO - new user registered in DB with the id: 11
2024-02-21 11:36:51,963 - INFO - user with google id is not in DB registering the user and then will be outputing the data
2024-02-21 11:36:51,963 - INFO - the google-user record found in DB: <app.db.models.User object at 0x7f68121fe0e0>
2024-02-21 11:36:51,964 - INFO - Registering the new user in DB with google login
2024-02-21 11:36:51,964 - INFO - JWT token created for the data of the user
2024-02-21 11:36:51,964 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-21 11:36:55,914 - INFO - the google-user record found in DB: <app.db.models.User object at 0x7f68120e5090>
2024-02-21 11:36:55,914 - INFO - user record already in database by email
2024-02-21 11:36:55,915 - INFO - JWT token created for the data of the user
2024-02-21 11:36:55,915 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-21 11:38:24,848 - INFO - the user record found in DB: <app.db.models.User object at 0x7f68120e51b0>
2024-02-21 11:38:24,848 - INFO - Finding if user record exist in DB
2024-02-21 11:38:24,848 - INFO - checking the user credentials if correct than access will be given
2024-02-21 11:38:25,133 - INFO - JWT token created for the data of the user
2024-02-21 11:38:25,133 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-21 11:38:25,133 - INFO - JWT refresh token created for the user data
2024-02-21 11:38:25,133 - INFO - returning the refresh token generated from jwt_access_token() funtion
