2024-02-15 11:11:18,451 - INFO - Attempting to register user abrar@gmail.com
2024-02-15 11:11:18,452 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-15 11:11:18,907 - INFO - new user registered in DB with the id: 9
2024-02-15 11:11:18,907 - INFO - new user is created Abrar
2024-02-15 11:11:18,907 - INFO - User sucessfully added
2024-02-15 11:11:49,996 - INFO - the user record found in DB: <app.db.models.User object at 0x7f9510f9f850>
2024-02-15 11:11:49,996 - INFO - Finding if user record exist in DB
2024-02-15 11:11:49,997 - INFO - checking the user credentials if correct than access will be given
2024-02-15 11:11:50,297 - ERROR - Error occured in authenticate_user : unsupported type for timedelta minutes component: str
2024-02-15 11:11:50,297 - ERROR - Error occured in signin: 400: unsupported type for timedelta minutes component: str
2024-02-15 11:13:02,227 - INFO - the user record found in DB: <app.db.models.User object at 0x7f2081616860>
2024-02-15 11:13:02,227 - INFO - Finding if user record exist in DB
2024-02-15 11:13:02,227 - INFO - checking the user credentials if correct than access will be given
2024-02-15 11:13:02,227 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-15 11:13:02,534 - ERROR - Error occured in authenticate_user : unsupported type for timedelta minutes component: str
2024-02-15 11:13:02,535 - ERROR - Error occured in signin
2024-02-15 11:14:52,439 - INFO - the user record found in DB: <app.db.models.User object at 0x7f6de2c16860>
2024-02-15 11:14:52,439 - INFO - Finding if user record exist in DB
2024-02-15 11:14:52,439 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-15 11:14:52,755 - ERROR - Error occured in authenticate_user : unsupported type for timedelta minutes component: str
2024-02-15 11:15:56,671 - INFO - the user record found in DB: <app.db.models.User object at 0x7f813c01a860>
2024-02-15 11:15:56,671 - INFO - Finding if user record exist in DB
2024-02-15 11:15:56,671 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-15 11:15:56,984 - ERROR - Error occured in authenticate_user
2024-02-15 11:17:33,868 - INFO - the user record found in DB: <app.db.models.User object at 0x7f189c80a860>
2024-02-15 11:17:33,868 - INFO - Finding if user record exist in DB
2024-02-15 11:17:33,868 - INFO - verifying user
2024-02-15 11:17:33,868 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-15 11:17:34,194 - ERROR - Error occured in authenticate_user
2024-02-15 11:19:06,932 - INFO - the user record found in DB: <app.db.models.User object at 0x7f189c865480>
2024-02-15 11:19:06,932 - INFO - Finding if user record exist in DB
2024-02-15 11:19:06,932 - INFO - verifying user
2024-02-15 11:19:07,225 - ERROR - Error occured in authenticate_user
2024-02-15 11:21:53,174 - INFO - the user record found in DB: <app.db.models.User object at 0x7fbc7bc1a860>
2024-02-15 11:21:53,174 - INFO - Finding if user record exist in DB
2024-02-15 11:21:53,174 - INFO - checking the user credentials if correct than access will be given
2024-02-15 11:21:53,174 - INFO - verifying user
2024-02-15 11:21:53,175 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-15 11:21:53,487 - INFO - JWT token created for the data of the user
2024-02-15 11:21:53,487 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-15 11:23:33,937 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-15 11:23:33,937 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-15 11:23:33,937 - INFO - the user ID extracted from token in decode: 9
2024-02-15 11:23:33,937 - INFO - the user id after decoding: 9
2024-02-15 11:23:33,937 - ERROR - Error occured while rollouting billboard: module 'logging' has no attribute 'infp'
2024-02-15 11:24:05,935 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-15 11:24:05,935 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-15 11:24:05,936 - INFO - the user ID extracted from token in decode: 9
2024-02-15 11:24:05,936 - INFO - the user id after decoding: 9
2024-02-15 11:24:05,936 - INFO - data: {'location': 'Thal', 'price': 150000, 'size': '1000x1000', 'status': 'Avaliable', 'register_date': '15-feb-2024', 'picture': 'http://billboard.com/picture-thal.png', 'fk_user_id': 9}
2024-02-15 11:24:05,937 - INFO - RolloutBillBoard table is recieving data from crud rollout_billboard
2024-02-15 11:24:23,253 - INFO - Taking all the Billboards data in crud operations which is accessing RollOutBillBoards table
2024-02-15 11:25:57,996 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-15 11:25:57,996 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-15 11:25:57,997 - INFO - the user ID extracted from token in decode: 9
2024-02-15 11:25:58,040 - INFO - Booking done the id is: 6
2024-02-15 11:26:25,492 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-15 11:26:25,492 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-15 11:26:25,492 - INFO - the user ID extracted from token in decode: 9
2024-02-15 11:26:25,492 - INFO - the user id after decoding: 9
2024-02-15 11:26:41,302 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-15 11:26:41,302 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-15 11:26:41,302 - INFO - the user ID extracted from token in decode: 9
2024-02-15 11:26:41,302 - INFO - the user id after decoding: 9
2024-02-15 11:26:41,302 - INFO - returning my booked billboards from crud funtion my_booked_billboards which is accessing BookBillBoard table
2024-02-15 11:27:06,315 - INFO - the user record found in DB: <app.db.models.User object at 0x7fafbc72e860>
2024-02-15 11:27:06,315 - INFO - Finding if user record exist in DB
2024-02-15 11:27:06,315 - INFO - checking the user credentials if correct than access will be given
2024-02-15 11:27:06,315 - INFO - verifying user
2024-02-15 11:27:06,316 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/islam/Documents/K2X-Tech/rollout_k2x/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-02-15 11:27:06,626 - INFO - JWT token created for the data of the user
2024-02-15 11:27:06,626 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-15 11:27:23,217 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-15 11:27:23,217 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-15 11:27:23,218 - INFO - the user ID extracted from token in decode: 9
2024-02-15 11:27:23,218 - INFO - the user id after decoding: 9
2024-02-15 11:33:33,999 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-15 11:33:33,999 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-15 11:33:33,999 - ERROR - Error occured in jwt_token_decode helper function
2024-02-15 11:33:49,451 - INFO - the user record found in DB: <app.db.models.User object at 0x7fafbc78a500>
2024-02-15 11:33:49,451 - INFO - Finding if user record exist in DB
2024-02-15 11:33:49,451 - INFO - checking the user credentials if correct than access will be given
2024-02-15 11:33:49,451 - INFO - verifying user
2024-02-15 11:33:49,735 - INFO - JWT token created for the data of the user
2024-02-15 11:33:49,736 - INFO - returning the token generated from jwt_access_token() funtion
2024-02-15 11:34:00,908 - INFO - token have two parts some time writen as token "value of token" or directly "token"
2024-02-15 11:34:00,909 - INFO - trying to decode token and extract the ID from it so it will be used in foreign key
2024-02-15 11:34:00,909 - INFO - the user ID extracted from token in decode: 9
